import {
  FaAd,
  FaAudioDescription,
  FaBatteryFull,
  FaBrain,
  FaBuilding,
  FaCamera,
  FaCar,
  FaCarBattery,
  FaCarSide,
  FaChargingStation,
  FaClock,
  FaComments,
  FaDatabase,
  FaDoorClosed,
  FaGamepad,
  FaHospital,
  FaHotel,
  FaLandmark,
  FaLaptopCode,
  FaMicrochip,
  FaNetworkWired,
  FaParagraph,
  FaRoute,
  FaRuler,
  FaRulerCombined,
  FaRulerHorizontal,
  FaRulerVertical,
  FaShippingFast,
  FaStop,
  FaStore,
  FaTemperatureHigh,
  FaUsers,
  FaVoicemail,
  FaWalking,
  FaWeight,
  FaWeightHanging,
  FaWifi,
} from "react-icons/fa";

const ICONS = {
  FaAd,
  FaAudioDescription,
  FaBatteryFull,
  FaBrain,
  FaBuilding,
  FaCamera,
  FaCar,
  FaCarBattery,
  FaCarSide,
  FaChargingStation,
  FaClock,
  FaComments,
  FaDatabase,
  FaDoorClosed,
  FaGamepad,
  FaHospital,
  FaHotel,
  FaLandmark,
  FaLaptopCode,
  FaNetworkWired,
  FaParagraph,
  FaRoute,
  FaRuler,
  FaRulerCombined,
  FaRulerHorizontal,
  FaRulerVertical,
  FaShippingFast,
  FaStop,
  FaStore,
  FaTemperatureHigh,
  FaUsers,
  FaVoicemail,
  FaWalking,
  FaWeight,
  FaWeightHanging,
  FaWifi,
};

export function SpecIcon({ name, ...props }) {
  const Comp = ICONS[name] || FaMicrochip;
  return <Comp {...props} />;
}
