import {
  FaAd,
  FaAudioDescription,
  FaBatteryFull,
  FaBoxOpen,
  FaBrain,
  FaBuilding,
  FaBullhorn,
  FaCamera,
  FaCar,
  FaCarBattery,
  FaCarSide,
  FaChargingStation,
  FaChartLine,
  FaClock,
  FaCogs,
  FaComments,
  FaDatabase,
  FaDoorClosed,
  FaFlask,
  FaGamepad,
  FaGraduationCap,
  FaHospital,
  FaHotel,
  FaLandmark,
  FaLaptopCode,
  FaMapMarkedAlt,
  FaMicrochip,
  FaNetworkWired,
  FaParagraph,
  FaRobot,
  FaRoute,
  FaRuler,
  FaRulerCombined,
  FaRulerHorizontal,
  FaRulerVertical,
  FaShippingFast,
  FaSpider,
  FaStop,
  FaStore,
  FaTags,
  FaTemperatureHigh,
  FaTruck,
  FaUsers,
  FaVoicemail,
  FaWalking,
  FaWarehouse,
  FaWeight,
  FaWeightHanging,
  FaWifi,
} from "react-icons/fa";
import ScreenIcon from "../components/icons/ScreenIcon.jsx";
import LanguagesIcon from "../components/icons/LanguagesIcon.jsx";
import RuntimeIcon from "../components/icons/RuntimeIcon.jsx";

const ICONS = {
  IconScreen: ScreenIcon,
  IconLanguages: LanguagesIcon,
  IconRuntime: RuntimeIcon,
  FaAd,
  FaAudioDescription,
  FaBatteryFull,
  FaBoxOpen,
  FaBrain,
  FaBuilding,
  FaBullhorn,
  FaCamera,
  FaCar,
  FaCarBattery,
  FaCarSide,
  FaChargingStation,
  FaChartLine,
  FaClock,
  FaCogs,
  FaComments,
  FaDatabase,
  FaDoorClosed,
  FaFlask,
  FaGamepad,
  FaGraduationCap,
  FaHospital,
  FaHotel,
  FaLandmark,
  FaLaptopCode,
  FaMapMarkedAlt,
  FaNetworkWired,
  FaParagraph,
  FaRobot,
  FaRoute,
  FaRuler,
  FaRulerCombined,
  FaRulerHorizontal,
  FaRulerVertical,
  FaShippingFast,
  FaSpider,
  FaStop,
  FaStore,
  FaTags,
  FaTemperatureHigh,
  FaTruck,
  FaUsers,
  FaVoicemail,
  FaWalking,
  FaWarehouse,
  FaWeight,
  FaWeightHanging,
  FaWifi,
};

export function SpecIcon({ name, ...props }) {
  const Comp = ICONS[name] || FaMicrochip;
  return <Comp {...props} />;
}
